# Generated by Django 4.2.4 on 2024-01-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_price', models.FloatField()),
                ('item_description', models.TextField()),
                ('item_id', models.IntegerField()),
                ('item_availavility', models.BooleanField(default=True)),
                ('item_discount', models.FloatField()),
                ('item_final_price', models.FloatField()),
            ],
        ),
    ]
